### ISSUE TITLE
when will  webhook be supported？ featureprob event can be forwarded to private system

### ISSUE THREAD

**Issue by daoleo** [FeatureProbe/FeatureProbe#11] opened 2022-10-21 03:05 UTC

**Comment by FengShang** [comment] 2022-11-25 02:42
Duplicate of #17

**Comment by FengShang** [comment] 2022-12-08 03:28
Find webhook here:

![Image](https://user-images.githubusercontent.com/1624616/206349561-8fbd1b7a-d8c0-4c19-86e4-3d8da9cab562.png)

**Closed by FengShang** 2022-12-08 03:28 UTC
Labels: duplicate, enhancement
